{% set name = "dynamotable" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alisterburt/dynamotable/archive/v{{ version }}.tar.gz
  sha256: ae91fc92ccfec7671bbcd885fb6e5edcd8bd3e5d3250feeb97357dfa64ca1b00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pandas
    - pip
    - python >=3.6
  run:
    - pandas
    - python >=3.6

test:
  imports:
    - dynamotable
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisterburt/dynamotable
  summary: dynamotable is a Python package to facilitate reading and writing of table files from the Dynamo subtomogram averaging package
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alisterburt
    - goanpeca
